In [3]:
import numpy as np

target = np.array([0] * 10 + [1] * 10)
target  # 10개의 0(Negative), 10개의 1(Positive)를 가짐

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
pred = np.array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])
pred

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])

In [5]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target, pred)   # 혼동행렬 만들기

array([[7, 3],
       [2, 8]])

In [6]:
from sklearn.metrics import precision_score, recall_score
print('정밀도 :', precision_score(target, pred))
print('재현률 :', recall_score(target, pred))

from sklearn.metrics import accuracy_score, f1_score
print('정확도 :', accuracy_score(target, pred))
print('F1 점수 :', f1_score(target, pred))

정밀도 : 0.7272727272727273
재현률 : 0.8
정확도 : 0.75
F1 점수 : 0.761904761904762


In [ ]:
import numpy as np
from sklearn import metrics 

# 닥스 훈트의 몸 길이와 몸 높이
dach_length = [77, 78, 85, 83, 73, 77, 73, 80]
dach_height = [25, 28, 19, 30, 21, 22, 17, 35]

# 사모예드의 몸 길이와 몸 높이
samo_length = [75, 77, 86, 86, 79, 83, 83, 88]
samo_height = [56, 57, 50, 53, 60, 53, 49, 61]

d_data = np.column_stack((dach_length, dach_height))
d_label = np.zeros(len(d_data))   # 닥스훈트는 0으로 레이블링
s_data = np.column_stack((samo_length, samo_height))
s_label = np.ones(len(s_data))   # 사모예드는 1로 레이블링

# 사모예드와 닥스 훈트의 길이, 높이 데이터는 생략한다
# 개의 길이와 높이를 각각 ndarray 형태로 만든다
dog_length = np.array(dach_length + samo_length) # 리스트를 이어 ndarray로
dog_height = np.array(dach_height + samo_height) # 리스트를 이어 ndarray로

dog_data = np.column_stack((dog_length, dog_height))

plt.title("Dog data without label")
plt.scatter(dog_length, dog_height)

### LAB 5-1: 붓꽃 데이터를 군집화

In [7]:
from sklearn import cluster
from sklearn.datasets import load_iris 
import numpy as np

iris = load_iris() 
k = len(iris.target_names)  # 몇 개의 군집으로 나눌지를 결정한다

In [8]:
print('kMeans() 군집화 적용...')
model = cluster.KMeans(n_clusters=k)
model.fit(iris.data)
labels = model.predict(iris.data)
print('군집화 결과 labels :', labels)
a_counts = np.bincount(labels[:50])
b_counts = np.bincount(labels[50:100])
c_counts = np.bincount(labels[100:])

kMeans() 군집화 적용...
군집화 결과 labels : [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]


In [9]:
d ={ 0: np.argmax(a_counts), 1: np.argmax(b_counts), 2 : np.argmax(c_counts)}
new_labels = np.copy(labels)
for old, new in d.items():
    new_labels[labels == old] = new

print('다시 레이블링을 한 후의 new_labels =', new_labels)

다시 레이블링을 한 후의 new_labels = [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1
 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 0 1
 1 0]
